Exercise-1


In [ ]:
def Length(x,type):
  if (type=="m"):
    result=x*3.28
  elif(type=="ft"):
    result=x/3.28
  return result

def Weight(x,type):
  if (type=="kg"):
    result=x*2.20
  elif(type=="lb"):
    result=x/2.20
  return result

def Volume(x,type):
  if (type=="ltr"):
    result=x*3.78
  elif(type=="gal"):
    result=x/3.78
  return result


conversion=input("Enter the type of measurement you would like to convert(length, weight, volume): ")
a=input("Enter the value to be converted: ")
try:
    a=int(a)
except:
    print("Invalid input")
type=input("Enter the type of value you have entered: m,ft,kg,lb,ltr,gal: ")
if conversion=="length":
  print(Length(a,type))
elif conversion=="weight":
  print(Weight(a,type))
elif conversion=="volume":
  print(Volume(a,type))
else:
  print("Invalid")

Enter the type of measurement you would like to convert(length, weight, volume): weight
Enter the value to be converted: 85
Enter the type of value you have entered: m,ft,kg,lb,ltr,gal: kg
187.00000000000003


Exercise 2

In [ ]:
def calculate_total(values):
    # Receives a list and returns the total sum of its elements
    total = 0
    for num in values:
        total += num
    return total

def compute_average(values):
    # Receives a list and returns the mean value of its elements
    total = 0
    for num in values:
        total += num
    return total / len(values)

def get_highest(values):
    # Returns the largest element in the given list
    return max(values)

def get_lowest(values):
    # Returns the smallest element in the given list
    return min(values)

user_input = input("Provide numbers separated by spaces: ")
try:
    numbers = [int(i) for i in user_input.split() if i.isdigit()]
except:
    print("Please enter valid numeric values.")

operation = input("Select an operation: sum, average, maximum, minimum: ")

match operation:
    case "sum":
        print("Total sum:", calculate_total(numbers))
    case "average":
        print("Computed average:", compute_average(numbers))
    case "maximum":
        print("Largest number:", get_highest(numbers))
    case "minimum":
        print("Smallest number:", get_lowest(numbers))


Provide numbers separated by spaces: 2 6 8 10 4
Select an operation: sum, average, maximum, minimum: sum
Total sum: 30


Exercise - 3

In [ ]:
def extract_every_other(lst):
    if not isinstance(lst, list):
        raise TypeError("Input must be a list.")
    return [item for idx, item in enumerate(lst) if idx % 2 == 0]
print(extract_every_other([2, 4, 6, 8, 6, 4]))


[2, 6, 6]


Exercise - 4

In [ ]:
def get_sublist(lst, start, end):
  """
    Returns a sublist from a given start to end index.

    Args:
        lst (list): The input list.
        start (int): The starting index (inclusive).
        end (int): The ending index (inclusive).

    Returns:
        list: The extracted sublist.
    """
  sub_lst = lst[start:end + 1]  # Extract sublist
  return sub_lst

print(get_sublist([10, 20, 30, 40, 50, 60], 2, 4))

[30, 40, 50]


Exercise - 5

In [ ]:
def reverse_list(lst):
    """
    Reverses the order of elements in a given list.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list with elements in reverse order.
    """
    rev_lst = lst[::-1]  # Reverse the list
    return rev_lst

print(reverse_list([10, 20, 30, 40, 50, 60]))


[60, 50, 40, 30, 20, 10]


Exercise - 6

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last element from a given list.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list with the first and last elements removed.
    """
    trimmed_lst = lst[1:len(lst) - 1]  # Slice out first and last element
    return trimmed_lst

print(remove_first_last([10, 20, 30, 40, 50]))


[20, 30, 40]


Exercise - 7

In [ ]:
def get_first_n(lst, n):
    """
    Returns the first 'n' elements from a given list.

    Args:
        lst (list): The input list.
        n (int): The number of elements to retrieve.

    Returns:
        list: A new list containing the first 'n' elements.
    """
    first_n = lst[:n]  # Get first 'n' elements
    return first_n

print(get_first_n([10, 20, 30, 40, 50], 3))


[10, 20, 30]


Exercise - 8

In [ ]:
def get_last_n(lst, n):
    """
    Returns the last 'n' elements from a given list.

    Args:
        lst (list): The input list.
        n (int): The number of elements to retrieve.

    Returns:
        list: A new list containing the last 'n' elements.
    """
    last_n = lst[len(lst) - n:]  # Get last 'n' elements
    return last_n

print(get_last_n([10, 20, 30, 40, 50], 2))


[40, 50]


Exercise - 9

In [ ]:
def reverse_skip(lst):
    """
    Reverses the list and returns every alternate element starting from the second one.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list with elements reversed and every alternate element skipped.
    """
    rev_lst = lst[::-1]  # Reverse the list
    skipped_lst = rev_lst[1::2]  # Take alternate elements
    return skipped_lst

print(reverse_skip([10, 20, 30, 40, 50, 60]))


[50, 30, 10]


Exercise - 10

In [ ]:
def flatten(lst):
    """
    Flattens a nested list (one level deep) into a single list.

    Args:
        lst (list): A list containing sublists.

    Returns:
        list: A new list with all elements from the nested sublists combined into a single list.
    """
    flat_lst = []  # Store flattened elements
    for sublist in lst:
        for item in sublist:
            flat_lst.append(item)
    return flat_lst

print(flatten([[10, 20, 30], [40, 50, 60]]))


[10, 20, 30, 40, 50, 60]


Exercise - 11

In [ ]:
def access_nested_element(lst, indices):
    """
    Accesses an element from a nested list using a list of indices.

    Args:
        lst (list): The input nested list.
        indices (list): A list of indices used to access the desired element.

    Returns:
        The element located at the specified indices.

    Raises:
        IndexError: If an index is out of range for the given list structure.
    """
    for index in indices:
        lst = lst[index]  # Navigate through indices
    return lst

print(access_nested_element([[10, 20, 30], [40, 50, 60], [70, 80, 90]], [1, 2]))


60


Exercise - 12

In [ ]:
def sum_nested(lst):
    """
    Sums all elements in a nested list, including sublists.

    Args:
        lst (list): The input nested list, which may contain numbers or sublists.

    Returns:
        int: The total sum of all elements in the nested list.
    """
    total = 0  # Store sum
    for sub in lst:
        if isinstance(sub, list):
            for val in sub:
                if isinstance(val, list):
                    for num in val:
                        total += num
                else:
                    total += val
        else:
            total += sub
    return total

print(sum_nested([[10, 20], [30, [40, 50]], 60]))


210


Exercise - 13

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Args:
        lst (list): The input nested list, which may contain numbers or sublists.
        elem: The element to be removed from the list.

    Returns:
        list: The modified list with the specified element removed from all sublists.
    """
    for sub in lst:
        for val in sub:
            if val == elem:
                sub.remove(val)
    return lst

print(remove_element([[10, 20], [30, 20], [40, 50]], 20))


[[10], [30], [40, 50]]


Exercise - 14

In [ ]:
def find_max(lst):
    """
    Finds the maximum number in a nested list, which may contain other lists.

    Args:
        lst (list): The input nested list, which may contain numbers or sublists.

    Returns:
        int or float: The maximum number found in the nested list.
    """
    max_val = float('-inf')  # Initialize with smallest possible value
    for sub in lst:
        if isinstance(sub, list):
            for val in sub:
                if isinstance(val, list):
                    for num in val:
                        if num > max_val:
                            max_val = num
                else:
                    if val > max_val:
                        max_val = val
        else:
            if sub > max_val:
                max_val = sub
    return max_val

print(find_max([[10, 20], [30, [40, 50]], 60]))


60


Exercise - 15

In [ ]:
def count_occurences(lst, elem):
    """
    Counts the occurrences of a specific element in a nested list.

    Args:
        lst (list): The input nested list, which may contain numbers or sublists.
        elem: The element whose occurrences are to be counted.

    Returns:
        int: The count of occurrences of the specified element in the nested list.
    """
    count = 0  # Count occurrences
    for sub in lst:
        for val in sub:
            if val == elem:
                count += 1
    return count

print(count_occurences([[10, 20], [30, 20], [40, 20]], 20))


3


Exercise - 16

In [ ]:
def deep_flatten(lst):
    """
    Flattens a nested list (of arbitrary depth) into a single list.

    Args:
        lst (list): The input nested list, which may contain numbers or sublists.

    Returns:
        list: A new list with all elements from the nested sublists combined into a single list.
    """
    flat_lst = []  # Store flattened elements
    for sub in lst:
        if isinstance(sub, list):
            for val in sub:
                if isinstance(val, list):
                    for num in val:
                        flat_lst.append(num)
                else:
                    flat_lst.append(val)
        else:
            flat_lst.append(sub)
    return flat_lst

print(deep_flatten([[10, 20], [30, [40, 50]], 60]))


[10, 20, 30, 40, 50, 60]


Exercise - 17

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all numbers in a nested list.

    Args:
        lst (list): The input nested list, which may contain numbers or sublists.

    Returns:
        float: The average of all the numbers in the nested list.
    """
    total = 0  # Store sum
    count = 0  # Count elements
    for sub in lst:
        for val in sub:
            total += val
            count += 1
    return total / count  # Calculate average

print(average_nested([[10, 20], [30, 40], [50, 60]]))


35.0


Exercise-10 NUMPY




In [ ]:
import numpy as np

In [ ]:
square_matrix = np.empty([2,2])
print(square_matrix)

[[2.30216646e-316 0.00000000e+000]
 [2.05833592e-312             nan]]


In [ ]:
rect_matrix = np.ones([4,2])

In [ ]:
a = np.full([2,2],6,dtype= int)

In [ ]:
b=np.zeros_like(a)

In [ ]:
c=np.ones_like(a)

In [ ]:
new_list = [1,2,3,4]
np.array(new_list)

array([1, 2, 3, 4])

Question 2


In [ ]:
d = np.arange(10,49)

In [ ]:
e = np.arange(0,9)
e.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
g = np.eye(3)

In [ ]:
f = np.random.random(size=30)
f.mean()

0.4748712850178034

In [ ]:
h = np.random.random(size = 100)
h.reshape(10,10)


array([[0.84746204, 0.33472517, 0.02211027, 0.23177367, 0.29023108,
        0.29440369, 0.46606844, 0.06560673, 0.5586054 , 0.78566273],
       [0.91470865, 0.20560412, 0.44979931, 0.12915816, 0.22085212,
        0.46761253, 0.05559444, 0.78211453, 0.87901893, 0.89128576],
       [0.93635123, 0.06422125, 0.39988678, 0.11122731, 0.00938823,
        0.6930762 , 0.61198871, 0.10308069, 0.69736162, 0.12337661],
       [0.38610329, 0.36625188, 0.10899625, 0.11952389, 0.73342533,
        0.44994732, 0.16120621, 0.93915173, 0.21034198, 0.87353621],
       [0.20946219, 0.62990797, 0.53693431, 0.30944637, 0.67945359,
        0.26819966, 0.9207948 , 0.34854646, 0.52222547, 0.36328485],
       [0.6466111 , 0.79553258, 0.44266177, 0.40255319, 0.88232943,
        0.30697293, 0.74930795, 0.01926479, 0.07221937, 0.72929921],
       [0.54817125, 0.26442438, 0.93422847, 0.81567499, 0.65859367,
        0.93565095, 0.51574765, 0.82465454, 0.56838113, 0.5993483 ],
       [0.01230036, 0.15598556, 0.6399277

In [ ]:
np.max(h)


0.9934520905319837

In [ ]:
np.min(h)

0.003274736266947298

In [ ]:
i = np.zeros(10)
new_value = 1
i[4] = new_value
print(i)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = [1,2,0,0,4,0]
new_arr = np.flip(arr)
print(new_arr)

[0 4 0 0 2 1]


In [ ]:
k = np.zeros((2,2))
k = np.pad(k, pad_width=1, mode='constant', constant_values=1)
print(k)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
z = np.zeros((8,8),dtype=int)
#to slice elements from index first row and fill the colums with one
#to slice from 0th row and fill with 1
z[1::2, ::2] = 1
z[::2, 1::2] = 1

for i in range(8):
  for j in range(8):
    print(z[i][j],end = " ")
  print()

0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


Question-3

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [ ]:
sum = np.add(x,y)
print(sum)


[[ 6  8]
 [10 13]]


In [ ]:
sum1 = np.add(v,w)
print(sum1)

[20 22]


In [ ]:
diff = np.subtract(x,y)
diff1 = np.subtract(v,w)
print("diff of x and y is:", diff)
print("diff of v and w is:", diff1)

diff of x and y is: [[-4 -4]
 [-4 -3]]
diff of v and w is: [-2 -2]


In [ ]:
product = np.multiply(2,x)
product1 = np.multiply(3,y)
product2 = np.multiply(4,v)
product3 = np.multiply(5,w)
print("x:", product)
print("y:", product1)
print("v:", product2)
print("w:", product3)

x: [[ 2  4]
 [ 6 10]]
y: [[15 18]
 [21 24]]
v: [36 40]
w: [55 60]


In [ ]:
dot = np.dot(v,w)
dot1 = np.dot(x,v)
dot2 = np.dot(x,y)
print("dot product of v and w :", dot)
print("dot product of x and v :", dot1)
print("dot product of x and y :", dot2)

dot product of v and w : 219
dot product of x and v : [29 77]
dot product of x and y : [[19 22]
 [50 58]]


In [ ]:
row = np.vstack((x,y))
column = np.hstack((v,w))
print(row)
print(column)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


In [ ]:
err = np.concatenate((x,v))
# we get an error ass the dimension of x and v are not same and to concatenate two arrays we require the same dimension for both inputs

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Question-4

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


In [ ]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.    1.  ]
 [ 1.75 -0.75]]


In [ ]:
proof = np.dot(A,A_inv)
print(np.round_(proof))

[[1. 0.]
 [0. 1.]]


In [ ]:
AB = np.dot(A,B)
print(AB)
BA = np.dot(B,A)
print(BA)


[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [ ]:
AB == BA

array([[False, False],
       [False, False]])

In [ ]:
trans = AB.transpose()
print(trans)

[[23 51]
 [13 29]]


In [ ]:
transA = A.transpose()
transB = B.transpose()
transBA = np.dot(transB,transA)
print(transBA)


[[23 51]
 [13 29]]


In [ ]:
trans == transBA

array([[ True,  True],
       [ True,  True]])

In [ ]:
mat_A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

mat_B = np.array([-1, -3, 9])


matA_inv = np.linalg.inv(mat_A)

X = np.dot(matA_inv, mat_B)

# Print the solution
print("Solution: x =", X[0], ", y =", X[1], ", z =", X[2])


Solution: x = 2.0 , y = 1.0 , z = -2.0
